### ISSUE TITLE
FEATURE REQUEST: Please add offline messaging

### ISSUE THREAD

**Issue by adip-linux** [adqn/CAAbot#2]
Please add offline messaging functionality using a .$command functionality, as below

`.tell $user $message`

This should instruct the bot to message the user in question when they log on.

**Comment by adqn** [comment]
Done, and next items on the agenda will be:
1. Updating this repo to reflect the production version currently in use
2. Modifying .tell behavior such online users are not immediately notified if they haven't been active in the channel at least 5 minutes prior to being sent a message 
A new issue will be opened for each item. Thanks!
